services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "pass"
    ports:
      - "5672:5672"  # Puerto para la comunicación con RabbitMQ
      - "15672:15672" # Interfaz web de administración
    networks:
      - e-commerce

networks:
  e-commerce:

volumes:
  mysql_data:
